### ISSUE TITLE
Need more helpful error messages from API

### ISSUE THREAD

**Issue by erbas** [mtzgroup/tccloud#28] opened 2021-10-14 19:54 UTC
This is the 500 I mentioned in the previous but report. User really needs more information.

```
  File "/Users/keiran/repos/nanoreactor2/nanoreactor/engine/base.py", line 446, in compute_gradient
    results = self.compute_blocking(geom, ('energy', 'gradient'), job_type=JobType.gradient, *args, **kwargs)
  File "/Users/keiran/repos/nanoreactor2/nanoreactor/engine/base.py", line 408, in compute_blocking
    results = [a for a in self.compute(geom, fields, job_type, *args, **kwargs)]
  File "/Users/keiran/repos/nanoreactor2/nanoreactor/engine/base.py", line 408, in <listcomp>
    results = [a for a in self.compute(geom, fields, job_type, *args, **kwargs)]
  File "/Users/keiran/repos/nanoreactor2/nanoreactor/engine/base.py", line 375, in compute
    raise result
  File "/Users/keiran/repos/nanoreactor2/nanoreactor/engine/base.py", line 260, in _process
    result = self.compute__(geom, job_type, workerid, *args, **kwargs)
  File "/Users/keiran/repos/nanoreactor2/nanoreactor/engine/tcc_new_engine.py", line 62, in compute__
    result = future_result.get()
  File "/Users/keiran/.local/lib/python3.8/site-packages/tccloud/models.py", line 119, in get
    while self.status not in _READY_STATES:
  File "/Users/keiran/.local/lib/python3.8/site-packages/tccloud/models.py", line 150, in status
    self.compute_status, self.result = self.client.result(self.to_task())
  File "/Users/keiran/.local/lib/python3.8/site-packages/tccloud/http_client.py", line 315, in result
    task_result = self._authenticated_request(
  File "/Users/keiran/.local/lib/python3.8/site-packages/tccloud/http_client.py", line 196, in _authenticated_request
    return self._request(
  File "/Users/keiran/.local/lib/python3.8/site-packages/tccloud/http_client.py", line 188, in _request
    response.raise_for_status()
  File "/Users/keiran/.local/lib/python3.8/site-packages/httpx/_models.py", line 1426, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 500 Server Error: Internal Server Error for url: https://tccloud.mtzlab.com/api/v1/compute/result
For more information check: https://httpstatuses.com/500
```

**Comment by coltonbh** [comment] 2021-10-14 23:20
Can you please provide specific inputs to reproduce error? 500 errors are generally not possible to generically provide better information on--they specifically mean "something completely unexpected went wrong on the server, so we have nothing more to say." Errors capable of better reporting are <500's (bad input, unauthorized, all 400's etc...).

Can you please file specifics here for a repo so I can look into it? Thanks!

**Comment by coltonbh** [comment] 2021-10-17 01:31
If you would like to address this issue, check out the code here: https://github.com/mtzgroup/tcpb-client/blob/162cecde1652a267ec1e956f16a34dccd539f436/tcpb/tcpb.py#L102-L113. This is the connection code that raises the error. Happy to review a PR you can submit there. Closing since this issue is related to TCPB. Feel free to log issue there and create a PR!

**Closed by coltonbh** 2021-10-17 01:31 UTC
